</div>
    <footer class="bg-light fixed-bottom mt-5">
      <div class="container">
        <div class="text-muted py-2 d-flex justify-content-between">
            <span>
                Author:
                <a href="https://github.com/awenzelhuemer" class="link-secondary">Andreas Wenzelhuemer</a></span>
            <?php $htmlOut(strftime('%c')); ?>
        </div>
      </div>
    </footer>
    <script src="js/bootstrap.bundle.min.js"></script>
</body>
</html>